[project]
name = "cmm-error-map"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "elfnor", email = "elfnor@gmail.com" }
]
dependencies = [
    "pyside6>=6.7.2",
    "numpy>=2.0.1",
    "scipy>=1.14.0",
    "pandas>=2.2.2",
    "matplotlib>=3.9.1",
    "ipython>=8.26.0",
    "pyqtgraph>=0.13.7",
    "ipympl>=0.9.4",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.2",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/cmm_error_map"]
