["KOBA 0620"]
title = "KOBA 0620"
nballs = [
    5,
    5,
]
ball_spacing = 133.0

["KOBA 0420"]
title = "KOBA 0420"
nballs = [
    5,
    5,
]
ball_spacing = 83.0

["KOBA 0320"]
title = "KOBA 0320"
nballs = [
    5,
    5,
]
ball_spacing = 60.0

["Step Gauge 0600"]
title = "Step Gauge 0600"
nballs = [
    31,
    1,
]
ball_spacing = 20.0

["APMP.L-S54n01.1"]
title = "APMP.L-S54n01.1"
nballs = [
    8,
    8,
]
ball_spacing = 50.0